FROM node:alpine 

#RUN  yum -y update \
#    && yum install -y gcc-c++ make 
#RUN  curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash - 
#RUN  yum install -y nodejs

WORKDIR '/app'
COPY package.json ./

RUN  npm install 

COPY . .
CMD ["npm", "run", "start"]

